import * as React from 'react'
import Layout from '../components/layout'
import { StaticImage } from 'gatsby-plugin-image'
import Seo from '../components/seo'

const AboutPage = () => {
  return (
     <Layout pageTitle="Den harmoniska kroppen">
<StaticImage
        alt="Clifford, a reddish-brown pitbull, dozing in a bean bag chair"
        src="../images/walk.jpg"
/>
     

<h3>Att andas</h3> 
<p>Andningen omspänner och mäter exakt ut hela vår livslängd, från det första skriket till det sista andetaget. Det är redo att fungera från det vi föds. Det är inte vår egen ansträngning och livserfarenhet som gör att  vi kan lita på den, utan det är den djupt liggande vishet som handlar i vårt omedvetna redan under fosterstadiet. Vid födelsen har hjärtat redan slagit sedan länge, och andningen anpassar undan för undan sin rytm till pulsen till dess den stabiliseras omkring förhållandet ett andetag på fyra hjärtslag. Andningens och hjärtverksamhetens regleringscentra ligger intill varandra i förlängda märgen, hjärnans allra djupaste och mest omedvetna skikt.</p>
<p>Vi behöver aldrig lära oss att andas. Den kunskap som reglerar andningen ligger före all medveten inlärning. Vi kan andas redan när vi föds, precis som vårt hjärta kan slå redan när vi föds. Vårt första skriḱ satte igång en dittills oanvänd men redan helt arbetsduglig funktion, som långsamt förfinas och anpassar sig för att följa varje etapp av människokroppens växande.</p>
<p>Andningens kemiska funktion är välbekant: att genom gasutbyte tillföra friskt syre till blodet och transportera bort koldioxid. Men andningens rytmiska funktilon är minst lika viktig. Medan hjärtat bestämmer rytmen för blodets cirkulation och därigenom den omedvetna ämnesomsättningen, står andningen i samklang med rytmen i våra handlingar, våra yttre rörelser. På det fysiska planet anpassar den sig till även de finaste nyanser i vår aktivitet.</p>
<h3>Andning och känslor</h3>
<p>På det psykiska planet är det i synnerhet det ständigt fluktuerande känslolivet som kommer till uttryck genom andningen: den blir hämmad när vi är rädda, mer intensiv när vi är arga, snabbare när vi åtrår och långsammare när vi är lugna. Utanför all systematisering och klassificering anpassar andningen sig smidigt till de ständiga förändringarna i vårt inre och yttre liv.</p>
<p>Vissa fysiska faktorer kan påverka andningssystemet direkt via inandningsluften: kyla, värme, fuktighet, luftföroreningar. Men det är förmodligen de emotionella påverkningarna som framför allt orsakar problem med andningen. Andningen visar sig vara känslornas omedelbara uttryck. Denna typ av störningar får oerhörda konsekvenser, som dessutom kan bli mycket långvariga eftersom de grundläggs redan under barndomen. Dessa frön, som psykoanalysen studerar på det psykologiska planet, kommer också att bära frukt på det fysiska planet i vuxen ålder och framför allt påverka andningen.</p>
<p>Det viktiga här är inte känslorna i sig utan om de accepteras eller förkastas av medvetandet. En känsla som accepteras helt och hållet kan liknas vid en eld, som fullständigt bränner upp allt stoff utan att lämna någon aska. När den emotionella vägen förklingat återtar det fysiska livet sitt lugn, precis som havet när vinden mojnat. Men om känslan förnekas och man i stället för "ja" svarar "nej" till den, även om bara till en del, så bildas det avfall, icke förbrända rester. Återgången till den inre friden och friheten blir inte fullständig, utan en lätt spänning finns kvar. Till en början är den alltför svag för att förnimmas, i synnerhet om det är fråga om ett barns ännu odifferentierade medvetnade.</p>
<p>Om dessa känslomässiga avståndstaganden upprepas får de en kumulativ effekt som leder till en muskulär sammandragning. Denna kommer i sin tur att påverka framför allt koordinationen av andningsrörelserna genom spänningar i halsen, bröstkorgen och buken. Andningen tvingas att hålla sig inom allt snävare gränser i en "bur" av låsta spänningar.</p>
<p>Det är mycket viktigt att klart skilja mellan känslan i sig, hur den uttrycks i beteende och övergår till handling.</p> 
<p>Känslan är en inre upplevelse som i sin tur kan leda till vissa yttre handlingar att fly från det som skrämmer oss, att förgöra det som framkallar vår vrede, att bemäktiga sig det vi längtar efter, ja till och med att beröva sig livet i förtvivlan.</p>
<p>Denna förbindelse mellan känsla och handling hindrar dock inte att det rör sig om två helt olika realiteter. Att hejda en destruktiv handling är en helt annan företeelse än att vägra att gå in i den inre känslomässiga upplevelsen: glädjen eller smärtan, fruktan eller vreden, längtan eller hatet. Kroppsligt sett står känslorna i förbindelse med de rytmiska funktionerna, hjärtslag och andning. Handlingen däremot uttrycks via det muskulära systemet och är förbunden med lemmarna.</p>
<p>Det är fullt möjligt att uppleva en ren känsla, liksom en våg som stiger, rullar våldsamt och så planar ut i vårt emotionella liv, utan att det leder till handlingar med katastrofala följder för oss själva eller för vår omgivning.</p>
<h3>Andningen vår inre terapeut</h3>
<p>Å ena sidan undergår andningen förändringar som orsakas av den motoriska aktiviteten och känslorna. Å andra sidan reglerar den själv rytmiskt alla yttre störningar. Liksom pendeln i ett ur strävar den hela tiden tillbaka till en regelbunden rytm. Den försöker absorbera alla yttre förändringar för att integrera dem i en stabil helhet. På så sätt spelar andningen en  terapeutisk roll av första rang.</p>
<p>En övning som utförs regelbundet kan hjälpa oss att dra största möjliga nytta av denna andningens naturliga roll. Andningsreflexerna kan bli våra bundsförvanter i försöken att upplösa konflikterna och gradvis också den bur av muskelspänningar som byggts upp av våra ackumulerade bortträngningar.</p>
<h3>Den centrala övningen</h3>
<p>För att undvika dom yttre hindren så mycket som möjligt skall vi i denna första övning gå tillbaka till den horisontella ställningen från vårt livs första början.</p>
<p><i>Lägg dig på rygg på golvet. Placera en kudde under huvudet så att det kommer upp några centimeter. Kuddens tjocklek kan variera från person till person. Det viktiga är att huvudet får stöd under bakhuvudet, så att halsen lämnas fri och huvudet varken faller bakåt av sin egen tyngd eller pressas framåt; med andra ord; det skall vara bekvämt.</i></p>
<p><i>Sträck ut benen utan att pressa dem mot varandra och låt fötterna falla utåt av sin egen tyngd. Om du i detta läge känner en sträckning i nedre delen av ryggen eller i buken, lägg då en kudde under knäna så att de lyfts upp några centimeter, och låt dem vila på kudden. Det räcker för att spänna av ländmusklerna, som förbinder låren med ryggraden. Spända ländmuskler kan nämligen medföra en känsla av stramning i hela ryggraden.</i></p>
<p><i>När knäna fått den rätta höjden över golvet känns det bekvämt för hela den nedre delen av kroppen.</i></p>
<p><i>Lossa på alla kläder så att ingenting sitter åt mot buken, bröstet eller halsen.</i></p>
<p><i>Lägg händerna på magen med handflatorna öppna och vända nedåt i trakten av solarplexus, dvs i maggropen mitt emellan naveln och spetsen av bröstbenet (benet mitt på bröstkorgens framsida). Låt armbågarna vila på golvet på ömse sidor av kroppen. I denna ställning kan armarna vila utan spänning med fingertopparna i kontakt med buken.</i></p>
<p><i>Håll munnen stängd och andas gemom näsan. Blunda, nu är du klar att börja.</i></p>
<h3>Frihet</h3>
<p><i>Var först uppmärksam på vad som sker under dina fingrar utan att påverka eller förändra någonting, vad det än må vara. Behåll bara kontakten, enkelt och naturligt, med området kring solarplexus.</i></p>
<p><i>Det är mycket möjligt att du till en början inte känner någoting särskilt, att allt verkar helt orörligt. Kanske har du ansträngt dig lite för mycket att vara uppmärksam och därigenom hejdat andningen? Om du märker det, försök då att helt enkelt lämna andningen fri att komma och gå precis som den vill. Se bara till att du inte blockerar den. Ge den tid att hitta sin plats och rytm.</i></p>
<p><i>Du kommer då att känna hur buken rör sig under dina fingrar, till en början nästan omärkligt. Denna rörelse är andningsrytmen som speglas på kroppens yta.</i></p> 
<p><i>Det är mycket viktigt att lämna andningen helt fri att själv söka sig fram till sin egen plats och rytm. Precis som den är, långsam eller snabb, regelbunden eller oregelbunden, är den riktig och rätt. Nöj dig med att lätt och naturligt iaktta hur den kommer och går, utan att ändra någonting.</i></p>
<p><i>Det kan hända att andningen avbryts av suckar eller gäspningar. Suckar och gäspningar är reflexstyrda mekanismer för att reglera andningen, och vi släpper fram, dem utan att hålla emot. Vi får till och med njuta av dem, helt och fullt, när de kommer. Eftersom de svarar mot organismens behov känns de behagliga. Det som kanske inte alltid är acceptabelt i en social situation är tvärtom extra välkommet nu under övningen. Men försök för den skull inte att framkalla dem med avsikt. Det räcker med att släppa fram den när de kommer av sig själva.</i></p>
<p><i>"Frihet" är alltså det första nyckelordet för denna övning. Att ge andningen fullständig frihet är det bästa sättet att samarbeta med den. Varje avsiktlig påverkan kommer bara att störa det subtila samspelet med den reflexstyrda regleringen.</i></p>
<p><i>Om vi lugnt iakttar andningen kan vi också konstatera att vi stör den både mycket och ofta. Mellan vårt medvetande som i bästa välvilja utför övningen och det djupt liggande samspelet från reflexer i vårt omedvetna kan vi urskilja ett mellanled av undermedvetna reaktioner. Det är detta nätverk av förvärvade vanor som stör den djupaste, medfödda regleringsförmågan. Dessa vanor kan inte förstöra mekanismen fullständigt, vilket skulle bli vår död, utan bara hämma den. Men det är tillräckligt för att ge oss obehag.</i></p>
<p><i>Att känna igen dessa störningar redan från första början, just när de visar sig, och utan ansträngning så mycket som möjligt låta andningen återfå sin frihet, det är den första aspekten av denna övning. Det innebär att vi återlämnar till kretsloppet av reflexer uppgiften att sköta andningen åt oss, vilket det klarar alldeles utmärkt på egen hand. Det handlar alltså inte om att anstränga sig, utan tvärtom att låta bli all onödig ansträngning.</i></p>
<h3>Mental närvaro</h3>
<p>Ordet frihet sammanfattar i allt väsentligt den fysiologiska aspekten av övningen. Nästa nyckelord berör den psykologiska aspekten: "närvaro" , mental närvaro. Samtidigt som vi på det kroppsliga planet ger andningen maximal frihet skall vi försöka att på det psykologiska planet behålla kontakten med den.</p>
<p>Denna kontakt kan det omedvetna inte ta ansvar för, som det gör med andningen. Det är i stället den "mentala närvaron" som gör denna subtila ansträngning möjlig. Ordet ansträngning är egentligen alltför otympligt att användas om denna lätta, naturliga aktivitet.</p>
<p>Att ta kontakt med bukens rörelser i andningen är lätt. Men det är lika lätt att förlora kontakten, den tycks vara lika snabbt funnen som försvunnen. Mycket snart börjar vi tänka på annat, vi blir distraherade och glömmer andningen. Efter en stund kommer vi plötsligt ihåg övningen och tar på nytt kontakt med den för att snart förlora den igen.</p>
<p>Bli inte förvånad över att uppmärksamheten kommer och går på detta sätt, det är i själva verket oundvikligt till en början. Bara den som aldrig på allvar har försökt att hålla kvar den mentala närvaron i oavbruten kontakt med någonting kan förvåna sig över det.</p>
<p>Om andningsmekanismen nu ter sig gammal, pålitlig, förtroendeingivande och i stånd att fungera felfritt hela livet igenom, så är den mentala närvaron en ny möjlighet i oss. Den utvecklas vid treårsåldern och ger oss då för första gången möjlighet att uppleva "jag är jag"! Den förstärks under ungdomsåren och går igenom en viktig stabiliseringsfas i tjugoårsåldern. Men den är hela tiden bräcklig och ostadig, som ett blinkande ljus.</p>
<p>Ibland finns den mentala närvaron där och låter oss möta den yttre omständigheterna  ansikte mot ansikte och i största mentala  klarhet fatta välunderbyggda och kreativa beslut och ta ansvar för våra handlingar och konsekvenserna av dem.</p>
<p>Men ofta, i själva verket allra oftast, finns den mentala närvaron inte där eller är nedbländad som en svag nattbelysning. Vi är tankspridda, överhopade av mentala och emotionella associationer utan något samband med nuet. Vi reagerar på det som händer i den aktuella situationen med automatismer som härrör från vårt förflutna, med vanor som vi knappt är medvetna om och som aldrig anpassar sig helt till det närvarande.</p> 
<p>Andningsreflexerna har vi fått gratis, men vår förmåga till mental närvaro behöver växa till sig. Den visar sig mer som en möjlighet än som en realitet. Att gradvis låta närvaron växa till, det är den psykologiska aspekten av övningen.</p>
<p>Det räcker med att återvända till kontakten med andningen via händerna på magen varje gång man vaknar upp ur sin distraktion. Övningen består just av denna rörelse fram och tillbaka. Det är i det naturliga och avspända försöket att om och om igen återta kontakten som en större stabilitet och kraft i den mentala närvaron växer fram.</p>
<p>Övingen bär frukt bara om den utförs lätt och utan tvång.</p>
<p>Försök inte att hålla kvar kontakten krampaktigt. En överdriven ansträngning leder bara till att du förlorar andningens frihet. Varje spänning, varje hämning av andningen är en larmsignal som berättar att du är knuten någonstans.</p>
<p>Den riktiga mentala närvaron kan liknas vid månljuset som speglas på en flod och utan någon tyngd vilar på vattenytan. Månljuset ligger tätt på varje våg utan att flytta på sig. Det lyser på det strömmande vattnet men hindrar inte dess flöde.</p>
<h3>Balans</h3>
<p>Övningens hjärtpunkt ligger i balansen mellan den fria andningen och den ogrumlade mentala närvaron. Där förenas de båda polerna i människans väsen.</p>
<p>Det omedvetnas pol förkroppsligas i ämnesomsättningsfunktionerna som har sitt centrum i buken. Det styrs av det vegetativa nervsystemet och de centra av hjärnan som ligger längst ner och närmast ryggmärgen.</p>
<p>Medvetandets pol representeras av perceptionens, tankens och jagmedvetandets klara funktioner. Denna pol har sitt centrum i huvudet och styrs av hjärnbarken, som är hjärnans yngsta del såväl i det enskilda embryots utvedcklig som i utvecklingen av hela människoarten.</p>
<p>Mellan dessa båda poler bildar andningen en rytmisk gräns, precis som dess viktigaste muskel, diafragman, delar bålen i två halvor. Andningen har en unik dubbelställning: den tillhör kroppens automatiska funktioner men kan samtidigt klart förnimmas av medvetandet, liksom vågen på  havets yta är en av oceanen men samtidigt förenar himmel och hav genom sin rytmiska rörelse.</p>
<p>Om vi fullföljer övningen utan att ha för avsikt att lyckas till varje pris, om vi bara lugnt fortsätter våra försök, kommer detta att inleda en process. Genom hela serien av försök och misslyckanden kommer den att bära frukt alldeles av sig själv när tiden är mogen.</p>
<h4>Kom bara ihåg: att öva är att försöka, inte att lyckas.</h4>
<h3>Övningens frukter</h3>
<p>Vissa resultat börjar märkas redan efter de allra första försöken, andra först efter upprepade övningar.</p>
<p>Vi går alla in i en övning som denna från olika utgångspunkter eftersom vi från födelsen bär på olika genetiskt bagage.</p>
<p>Mot denna personliga bakgrund sätter sedan vår egen historia, vårt livs materiella, sociala, känslomässiga och intellektuella förhållanden sina spår. Vanor bildas och många av dem sjunker ner i det omedvetna och påverkar oss utan att vi märker det. Två vuxna personer kan alltså inte starta utifrån en och samma utgångspunkt.</p>
<p>Den övning som föreslås här kan utföras på samma sätt av alla, eftersom den bygger på gemensamma element: andningsreflexer och mental närvaro. Men i vilken ordning resultaten följer, vilken betydelse de får och hur långvariga de blir kommer med nödvändighet att variera från person till person, beroende på hur vars och ens förvärvade vanor fungerar. Detta påpekande gäller för alla övningar som jag kommer att beskriva.</p>
<p>Jag vill ändå försöka ge några anvisningar. De första resultaten av övningarna kommer i synnerhet att beröra medvetandegörandet. Vissa fakta kommer att framstå klarare. Vårt intresse, som hittills framför allt har varit riktat mot yttervärlden, kommer att stimuleras av en mängd nya faktorer i förnimmelserna från den egna kroppen.</p>
<h3>Enhet</h3>
<p>Låt oss gå tillbaka til de första försöken: vi behåller kontakten med andningen just så som den visar sig fritt i solarplexusområdet under våra händer. Vi accepterar andningen sådan den är och ger den tid att vänja sig vid vår uppmärksamhet. Vi kommer att märka att den blir allt mera regelbunden efter hand, att bukens rörelser mer och mer börjar likna en våg som stiger och sjunker under våra fingrar och som av sig själv, liksom trevande, söker sin egen optimala rytm och plats.</p>
<p>Därpå konstaterar vi att rörelsen inte begränsas bara till det område där våra fingrar har uppmärksam kontakt. Efterhand kan vi känna att rörelsen blir regelbunden och allt tydligare hur den långsamt breder ut sig i hela buken och i hela bröstkorgen. Det ställe där våra fingrar vilar upplevs mer och mer som en passage, som en svängdörr mellan buken och bröstkorgen. Genom denna öppna dörr förenas den övre och den nedre delen av kroppen i rytmisk kontaḱt.</p>
<p>Genom att upprepa övningen dag efter dag kommer förnimmelserna att undan för undan bli allt tydligare. Andningsrörelsen som vi först bara förnimmer inom ett begränsat område tar så småningom hela kroppen i besittning, och bröstkorgen framstår som ett mekaniskt underverk. Den är konstruerad av ett spjälverk av revben för att skydda lungorna och hjärtat, och sammanfogad i lederna på så sätt att den i sin optimala funktion bjuder lika litet motstånd mot andningsvågen som de smidiga bukmusklerna.</p>
<p>På detta staduum kan det vara berikande att iaktta ett sovande spädbarn. När övningen gjort oss mer sensibla kan vi tydligare se hur barnets hela bål och hals engageras i andningen som en enda stor cell, levandegjord av en enda impuls. Och om barnet vaknar kommer vi att få se hur denna enhetliga rytm fortsätter vidare ut i armarna och benen när det skriker, gråter eller skrattar.</p>
<p>Övningen leder oss alltså mot en allt tydligare förnimmelse av enhet: kroppen som enhet när den utvidgas i inandningen och dras samman i utandningen: kroppens och psykets enhet i den oavbrutna kontakten mellan den stora andningsvågen och den mentala närvaron som är vittne till allt detta.</p>
<p>Efter en viss tid övning kommer till sist förnimmelsen av enhet att på ett naturligt sätt sprida ut även till det omgivande rummet. Andningen förenar i själv verket inte bara de båda polerna i vårt väsen utan också luften inne i kroppen och i det omgivande rummet i en oavbruten rörelse fram och tillbaka. Det är något som vi lätt kan göra oss medvetna om intellektuellt, men när övningen fördjupas kan den förvandla denna kunskap till en inifrån upplevd erfarenhet.</p>
<h3>Andningsmassage</h3>
<p>Vi upplever alltå ganska snart att när andningen lämnas fri och ostörd strävar den efter att sprida sin verkan till hela kroppen för att leda in den i en enhetlig rytm. Detta arbete utförs av en muskelkoordination som hör samman med lungornas arbete, men som också utsträcks till att omfatta hela bålen.</p>
<p>Denna utveckling tar ofta indirekta vägar. I försöken att gradvis återerövra en mera fullständig funktion möter andningskoordinationen i själva verket en rad hinder. Hela vårt livs samlade bortträngningar har lämnat spår efter sig i form av spänningar i kroppen. "Buren" som vi talat om tidigare framträder såväl i spänningar i de ytliggare liggande tvärstrimmiga musklerna som kramper i de inre organens glatta musklatur.</p>
<p>När andningen koordineras sätts den kraftfulla inre muskeln, diafragman, i förbindelse med en stor del av bålens ytligare liggande muskler. Den raka bukmuskeln täcker hela buken från bröstben till blygdben. Utanpå denna ligger de sneda bukmusklerna som förbinder revbenen med bäckenet på ömse sidor om bålen. I bröstkorgen deltar nätverket av interkostala muskler (mellan revbenen) i andningskoordinationen, som går vidare upp i halsen genom skalenerna (eller revbenshöjarmusklerna) och därigenom förbinder de översta revbenen med halskotorna.</p>
<p>Att avsiktligt låta andningen få tillbaka sin maximala frihet, det är att tillåta hela denna koordination att spela rollen av en inre massör. Den försöker mjukt och regelbundet lösa upp de samlade spänningarna och låter integrera deras energi i cirkulationen som helhet. Vid inandningen verkar massagen framför allt inifrån, under inverkan av diafragman, och vid utandningen framför allt från ytan, under inverkan av bukmusklerna.</p>
<p>Andningsmassagen fungerar på samma sätt hos alla, men de hinder den möter är olika hos var och en. De subjektiva upplevelserna och de individuella resultaten av andningsmassagen beror på dessa olikartade hinder. Det finns så många olika individuella reaktioner att vi bara kan nämna några få typiska exempel här. Man kan uppleva andningen som om den vore instängd i kroppen, liksom en flod som rinner i en trång och stenig flodbädd. Denna förnimmelse kommer att försvinna undan för undan i samma takt som andningen löser upp spänningarna, som när en flod sväller av regnet och rensar sin egen flodbädd.</p> 
<p>Olika ljud kan också höras torra eller dova knäppar från en ledförbindelse som frigörs i ryggraden eller i bröstkorgen, gurglande ljud från inre organ när en inre kramp släpper och cirkulationen fungerar på nytt i tarmar eller mage.</p>
<p>På olika ställen i kroppen kan också mer eller mindre ömmande punkter ge sig till känna. De motsvarar i allmänhet de kinesiska akupunkturpunkterna, som aktiveras reflexvägen. Förnimelsen intensifieras till en början för att sedan försvinna efter några minuter när cirkulationen stabiliserats.</p>
<p>Vissa förnimmelser kan återkomma i flera dagar eller till och med veckor varje gång man gör övningen, ända till dess man uppnått en mer stabil balans.</p>
<p>Liksom all annan massage engagerar andningsmassagen områden eller organ som inte befinner sig i balans, i en cykel som vanligen får följande förlopp:</p> 
<p> -- till en början ökar sensibiliteten i det område som kommit i balans till en nivå som bli smärtsam. Efter att ha passerat en höjdpunkt minskar förnimmelsen för att slutligen försvinna helt;</p>
<p> -- den följs av en eliminationsprocees som kan ta sig olika former, beroende på vilket organ som berörs och vilken grundtyp som dominerar hos vederbörande: diaréer, urinträngningar, kräkningar, svettningar, tårar, upphostningar, nysningar etc;</p>
<p> -- när elimineringen avslutas följer en period av trötthet och en känsla av avspänning;</p>
<p> -- slutligen ökar krafterna och medför en stabil känsla av välbefinnade som innebär att cykeln nått sitt slut.</p>
<p>Eftersom andningsmassagen arbetar mycket skonsamt och progressivt besparas man intensivt dramatiska reaktioner och går ofta igenom någon fas av cykeln utan att märka det.</p>
<p>Andningsarbetet bidrar också till att buken behåller sin form. Denna form är inte stel som resultatet av en viljemässig ansträngning att "hålla in magen", utan en fast men levande form. En buk som helt och fullt deltar i andningen utför dygnet runt de mjuka och kontinuerliga "bukövningar" som hjälper den att behålla sin tonus. Eftersom andningsrörelsen fungerar som en pendel är den lika effektiv när det gäller att aktivera alltför passsiva funktioner som att minska överspänningar. Beroende på individ och omständigheter kan övningen leda till att energin förnyas om man befinner sig i en period av trötthet eller till en ökad avspänning under en period då man "går på högt varv".</p>
<p>Andningen är inte minst en hjälp mot kroniska problem i matsmältningssystemet överkänslig eller förstoppad mage, aptitlöshet, kramper i tarmarna. Om matsmältningen och utsöndringen av avfallsprodukter förbättras återverkar detta i sin tur på helheten och ökar välbefinnandet och avspänningen. Ett av de snabbaste och allra vanligaste resultaten är en bättre sömn.</p>
<p>Jag har kort beskrivit de fysiologiska verkningar av andningsövningen som man i allmänhet först lägger märke till i praktiken. I nästa kapitel, i samband med den sittande övningen, skall vi tala om de psykologiska verkningarna.</p>
<h3>Övningens gränser</h3>
<p>Andningen  strävar visserligen alltid efter att återställa jamvikten men i den liggande ställningen med slutna ögon, som valts för denna första övning, ligger tonvikten snarare vid avspänning än vid aktivitet. Om en stegring av energin sedan blir resutatet, sker det indirekt. En avspänd kropp där blodet cirkulerar bättre utsöndrar sina avfallsprodukter och man känner sig uppfriskad efter övningen som efter en vederkvickande sömn.</p>
<p>I många avseenden gör man under övningen i full medvetenhet det som kroppen omedvetet gör under sömnen. Den mentala stabilisering som samtidigt behåller kontakten med andningen bidrar till att kroppen spänns av så att den återhämtar sig snabbare än om man bara helt enkelt lägger sig ned och dagdrömmer.</p>
<p>Erfarenheten visar emellertid att den liggande ställningen med slutna ögon lätt inbjuder till sömn. Om övningen pågår tillräckligt länge blir det allt svårare att hålla sig klarvaken. Den sömn som man då glider in i är i och för sig mycket välgörande för kroppen, men naturligtvis har vi då lämnat övningen.</p>
<p>En praktisk fråga: hur lång tid skall man ägna åt övningen för att nå märkbara resultat?</p>
<p>De mest djupgånde resultaten beror dels på hur regelbundet man övar, dels hur lång tid man sätter av varje gång. Låt säga att fem minuter varje gång är något av ett minimum. Om man har mera tid till förfogande och känner att man mår bra av övningen kan den utökas till tjugo minuter eller en halvtimme. Men man får inte göra den längre än vad som känns lustfyllt, man får inte tvinga sig. Utöver minimum på några minuter kan tiden variera beronde på omständigheterna och ens sinnesstämning för ögonblicket.</p> 
<p>Övningen blir mera effektiv om den utförs dagligen, helst vid samma tidpunkt varje gång. Den rytmiska regelbundenheten förstärker effekten. Det går bra vid vilken tid på dagen som helst. Om möjligt bör man alltid göra den på en särskild plats, precis som vi gör när vi kammar oss eller borstar tänderna.</p>
<p>Den övning som beskrivits här är så enkel till det yttre men den kan redan uppenbara många hemligheter för den som utför den regelbundet. Den kan utövas under månader och år och hela tiden förfinas och fördjupas. Den kan också bli det första steget i en metod som leder till allt mer komplexa övningar, som kommer att tas upp i de följande kapitlen. Men också då är det välgörande att återvända till detta första försök som en förberedelse för de andra övningarna eller under perioder då man är speciellt trött.</p>
<p>Hur det än ligger till, rekommenderar jag den läsare som vill följa mina råd i praktiken att utföra den liggande övningen under två till tre veckors tid innan man går vidare till den sittande övningen i nästa kapitel. Andningen frihet och den mentala kontakten med andningen leder till en trygghet som gör att man med lätthet kan gå vidare till nästa nivå.</p>
<h3>Kompletterande övningar</h3>
<p>I de allra flesta fall kan den beskrivna andningsövningen utföras direkt utan någon förberedelse.</p>
<p>Men det kan finnas tillfällen då man känner sig alltför nervös och spänd för att ha lust att lägga sig ned orörlig. Det känns som om man ligger på glödande kol och man står inte ut med att vara stilla.</p>
<p>Vid andra tillfällen känner man sig i stället alltför trött. Det rör sig inte om en trötthet orsakad av ett intensivt och långvarigt fysiskt arbete utan om den trötthet som uppkommer av en alltför långvarig hämning, som vi tvingat på vår kropp och våra känslor. Det kan hända att vi efter en dag på kontoret eller vid skrivbordet hemma, då vi inte haft några större möjligheter att röra på kroppen eller att ge uttryck för känslorna, känner att alla krafter är uttömda utan att vi har intryck av att vi uträttat någonting alls. I sådana fall har energin inte uttömts av någon ansträngning utan har helt enkelt stelnat i våra spänningar.</p>
<p>Det finns då några övningar som kan frigöra spänningarna och åter sätta igäng eneriflödet så att vi med gott resultat kan ägna oss åt andningsövningen. Här följer en kort serie övningar av detta slag. De kan också utföras sedan man lyssnat till andningen, särskilt om den övningen har gjorts längre. De nya övningarna kommer då att fungera som muskelväckare och blir på så sätt en fin övergång till den upprättstående kroppsställningen.</p>
<h3>Styrda sträckningar</h3>
<p><i> 1. Ligg på rygg med armarna på golvet brevid huvudet i kroppens förlängning och med raka ben.</i></p>
<p><i>Sträck undan för undan armar och ben åt var sitt håll, som för att förlänga dem och nå väggarna på rummets motsatta sidor. När du har sträckt lemmarna nära maximum men fortfarande känns behagligt, spänner du plötsligt av och låter kroppen passivt falla tillbaka som en tom säck på golvet.</i></p>
<p><i>Upprepa den växling mellan sträckning och avspänning ett tiotal gånger i den takt som känns bäst för dig.</i></p> 
<p><i> 2. Ligg på rygg i samma läge och stäck nu endast den högra sidan av kroppen: höger ben och höger arm. Spänn plötsligt av, precis som förut. Sträck därefter endast vänster sida: vänster arm och vänster ben, och spänn plötsligt av.</i></p>
<p><i>Fortsätt på samma sätt ett tiotal gånger och sträck växelvis den ena, växelvis den andra sidan i den takt som känns bäst för dig.</i></p>
<p><i>3. Ligg kvar i samma läge, men sträck ut armarna rakt åt sidorna, vinkla upp vristerna och tryck ut hälarna, knyt händerna och sträck dig som för att nå ut till alla fyra väggarna i rummet via de knutna händerna, hälarna och hjässan. Spänn plötsligt av, även händer och vrister.</i></p>
<p><i>Upprepa övningen ett tiotal gånger i den takt och med den kraft som känns bäst för dig.</i></p>
<p><i>4. Ligg på rygg, böj benen och för upp knäna mot bröstet. Fatta med händerna om knäna. Pressa undan för undan knäna mot bröstet medan du andas ut, så att kroppen dras samman till en liten boll. När sammandragningen når sitt maximum men fortfarande känns behaglig, släpper du med ens efter på armarnas tryck men håller kvar händerna runt knäna. Inandningen kommer då av sig själv, som av en elastisk fjädring, och du kan börja om på nytt.</i></p>
<p><i>Gör övningen fem gånger. Den hjälper dig att spänna av ryggen, om de föregående övningarna varit något för kraftiga, och att återställa tonusbalansen.</i></p> 
<h3>Gäspningar</h3>
<p><i>Vid slutet av var och en av de föregående övningarna kan du väcka gäspningsreflexen genom att utnyttja de ögonblick då kroppen efter spänningen åter spänner av. Det räcker med att bara låta munnen öppnas och mentalt inbjuda gäspningen att komma genom att tänka på den. </i></p>
<p><i>Det kan hända att den inte svarar på de första inviterna. Men om du upprepar inbjudan vid slutet av varje serie av sträcninngar kommer du till din överraskning att märka att reflexen utlöses allt lättare och lättare, och att det till sist räcker med att bara tänka på gäspningen för att den skall komma. Gäspningen är ett av våra naturligaste hjälpmedel för att lösa upp spänningar i diafragman och solarplexus. Den är ett sätt nå välbefinnande som vi snabbt kan bli förtrogna med och som kan hjälpa oss vid otaliga tillfällen. Jag känner till exempel skådespelare som använder sig av gäspningen för att bli av med rampfebern innan de går in på scenen.</i></p>
<h3>Spontana sträckningar</h3>
<p><i>Efter några serier av styrda sträckningar och några gäspningar kommer du att känna hur gäspningen av sig själv har en tendens att gå över i sträckningar av ryggen, armarna och benen, precis som hos ett spädbarn eller en katt som vaknar.</i></p>
<p><i>Försök då att gå in i de spontana sträckningarna och ge efter för dessa impulser; utnyttja all den kraft som finns i dem.</i></p>
<p>Dessa spontana, fria sträckningar, som regleras av det omedvetna allt efter musklernas tillfälliga behov, är också utmärkta hjälpmedel att spänna av. De är exempel på barnens och djurens naturliga gymnastik. Om du har möjlighet att regelbundet ta dig några minuter på golvet, uppmärksamt lyssna till sträckningsimpulserna och lämna fältet fritt för dem, så kommer de att bli allt säkrare och naturligare. Som belöning kommer du att finna ett verkligt nöje i att göra dem.</p>

    </Layout>
  )
}
export default AboutPage
